# Generated by Django 5.1.1 on 2024-11-18 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0007_list_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="shared_with",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
